services:
  pupper-robot:
    image: mini-pupper-robot:1.0
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - GAZEBO_MASTER_URI=http://localhost:5555
      - ROS_MASTER_URI=http://localhost:11311 
    network_mode: "host"
    privileged: true
    user: robomaker
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /home/ubuntu/environment/config:/config
      - /sys/class/pwm:/sys/class/pwm
      - /sys/bus/i2c/devices/3-0050/eeprom:/sys/bus/i2c/devices/3-0050/eeprom