# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:2.0

ADD robot_ws/src /home/robomaker/workspace/robot_ws/src
ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
RUN sudo rosdep fix-permissions && rosdep update
RUN sudo apt update
WORKDIR /home/robomaker/workspace/robot_ws

# dirty hack for mqtt bridge - latency in the container causes it to break without this
RUN sudo apt install -y ros-noetic-catkin python3-catkin-pkg python3-catkin-pkg-modules ros-noetic-mqtt-bridge
RUN sudo cp /home/robomaker/workspace/robot_ws/src/mqtt_bridge/src/mqtt_bridge/app.py /opt/ros/noetic/lib/python3/dist-packages/mqtt_bridge/app.py

# Build the Robot application
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y && colcon build"
RUN /bin/bash -c "sudo apt clean"

RUN sudo cp /home/robomaker/workspace/robot_ws/src/mqtt_bridge/src/mqtt_bridge/app.py /opt/ros/noetic/lib/python3/dist-packages/mqtt_bridge/app.py

# Add entrypoint script and grant permission
COPY scripts/robot-entrypoint.sh /home/robomaker/workspace/robot_ws
RUN sh -c 'sudo chmod +x robot-entrypoint.sh && sudo chown robomaker:robomaker robot-entrypoint.sh'

RUN sudo mkdir -p /config/certs/

ENV HARDWARE=true
ENV DANCE_CONFIG=/config/routines

CMD roslaunch mini_pupper_dance dance.launch hardware_connected:=${HARDWARE} dance_config_path:=${DANCE_CONFIG}
ENTRYPOINT [ "/home/robomaker/workspace/robot_ws/robot-entrypoint.sh" ]
